version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

  test:
    build:
      context: .
      target: test
    command: pytest /app/tests
    volumes:
      - .:/app
    env_file:
      - .env.docker
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
