version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
