"""Initial migration

Revision ID: 21605d9d3740
Revises: 
Create Date: 2024-04-07 16:03:04.232764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21605d9d3740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
