"""deleted raw data col

Revision ID: 2764e57b1663
Revises: 5c70e8782187
Create Date: 2024-05-23 14:16:51.841663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2764e57b1663'
down_revision = '5c70e8782187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('raw_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
