"""added email

Revision ID: 4858386e70e7
Revises: 3d783f75892b
Create Date: 2024-04-29 17:10:33.299656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4858386e70e7'
down_revision = '3d783f75892b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=127), nullable=False))
        batch_op.create_unique_constraint('unique_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
