"""added rows to store additional graph data

Revision ID: 5c70e8782187
Revises: 179342a6b6a0
Create Date: 2024-05-21 14:22:42.762281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c70e8782187'
down_revision = '179342a6b6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_to_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('id_to_parent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('id_to_children', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('id_to_children')
        batch_op.drop_column('id_to_parent')
        batch_op.drop_column('id_to_data')

    # ### end Alembic commands ###
