"""empty message

Revision ID: 5ee3aa7742f8
Revises: 6ee5a5f96a47
Create Date: 2024-05-14 15:28:25.630455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee3aa7742f8'
down_revision = '6ee5a5f96a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('graph_paths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('graph_roots', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.VARCHAR(length=127), nullable=False))

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('graph_roots')
        batch_op.drop_column('graph_paths')
        batch_op.drop_column('raw_data')

    # ### end Alembic commands ###
