"""added graph roots row

Revision ID: 62e8918d56dd
Revises: 031370f6796e
Create Date: 2024-05-07 00:24:01.437596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e8918d56dd'
down_revision = '031370f6796e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_roots', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('graph_roots')

    # ### end Alembic commands ###
