"""added raw csv data to dashboard model

Revision ID: 6eb59e118aed
Revises: f7f47a510130
Create Date: 2024-05-06 22:18:45.016080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb59e118aed'
down_revision = 'f7f47a510130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('raw_data')

    # ### end Alembic commands ###
