"""added email

Revision ID: f7f47a510130
Revises: 2f931574a81d
Create Date: 2024-05-03 19:51:36.510793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f47a510130'
down_revision = '2f931574a81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=127), nullable=False))
        batch_op.create_unique_constraint('unique_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
